(()=>{
 const startLocal=start,finishLocal=finish;
 let starting=false,pending=null;
 const dbReady=new Promise((resolve,reject)=>{const req=indexedDB.open('vendetta-verified-replays',1);req.onupgradeneeded=()=>req.result.createObjectStore('pending',{keyPath:'key'});req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});
 async function savePending(value){const db=await dbReady;return new Promise((resolve,reject)=>{const tx=db.transaction('pending','readwrite');tx.objectStore('pending').put(value);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
 async function deletePending(key){const db=await dbReady;return new Promise((resolve,reject)=>{const tx=db.transaction('pending','readwrite');tx.objectStore('pending').delete(key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
 async function loadPending(wallet){const db=await dbReady;return new Promise((resolve,reject)=>{const req=db.transaction('pending').objectStore('pending').getAll();req.onsuccess=()=>resolve(req.result.find(x=>x.wallet.toLowerCase()===wallet.toLowerCase()));req.onerror=()=>reject(req.error)})}
 function retryPanel(message){state='verifying';silenceCourtSounds();panel('<h2>VERIFYING YOUR MATCH</h2><p id="onlineVerifyMessage"></p><div class="row"><button class="primary" id="onlineRetry">RETRY VERIFICATION</button><button class="secondary" id="onlineBack">BACK TO STORY</button></div>');$('onlineVerifyMessage').textContent=message;$('onlineRetry').onclick=submit;$('onlineBack').onclick=storyHome}
 async function submit(){if(!pending)return;try{if(!window.vendettaOnline||window.vendettaOnline.wallet.toLowerCase()!==pending.wallet.toLowerCase())throw Error('Connect the same wallet to verify this match.');retryPanel('The server is replaying your match. No transaction is sent.');$('onlineRetry').disabled=true;const result=await window.vendettaOnline.submit(pending.ticket,pending.proof);await deletePending(pending.key);const local=pending.localRun;pending=null;vendettaReplay.stop();storyMemory.run={...local,stage:result.run.stage,lives:result.run.lives,earned:result.run.earned,closed:result.run.closed};storySave();storyActive=false;G=null;storyHome();const root=document.querySelector('.story-panel');const message=document.createElement('p');message.textContent=result.run.closed?'Run verified. Open Rewards to claim your points.':result.result.win?'Match verified. Continue to the next challenge.':'Match verified. One life used. You can retry this match.';root.prepend(message)}catch(e){retryPanel(e.message)}}
 start=async function(){if(!window.vendettaOnlineConfig?.enabled)return startLocal();if(starting)return;if(!window.vendettaOnline){storyPanel('<h2>CONNECT AGW TO PLAY ONLINE</h2><div id="storyWalletSlot"></div><button class="secondary" id="onlineStartBack">BACK</button>');$('onlineStartBack').onclick=storyHome;return}starting=true;try{const recovered=await loadPending(window.vendettaOnline.wallet);if(recovered){pending=recovered;retryPanel('A completed match is waiting for verification.');return}const r=storyMemory.run,entry=document.getElementById('storyPlay');const session=await window.vendettaOnline.prepareMatch(r);storySave();if(storyMemory.run!==r||!entry?.isConnected||state!=='story')return;if(session.run.stage!==r.stage||session.run.lives!==r.lives){r.stage=session.run.stage;r.lives=session.run.lives;r.earned=session.run.earned;storySave();storyIntro();return}vendettaReplay.record(session.ticket);startLocal()}catch(e){storyPanel('<h2>COULD NOT START ONLINE MATCH</h2><p id="onlineStartError"></p><div id="storyWalletSlot"></div><button class="secondary" id="onlineStartBack">BACK</button>');$('onlineStartError').textContent=e.message;$('onlineStartBack').onclick=storyHome}finally{starting=false}};
 window.addEventListener('vendetta-replay-complete',async e=>{if(!e.detail.ticket.serverRunId)return;const {ticket,proof}=e.detail;pending={key:ticket.wallet.toLowerCase()+':'+ticket.id,wallet:ticket.wallet,ticket,proof,localRun:structuredClone(storyMemory.run)};state='verifying';silenceCourtSounds();try{await savePending(pending);await submit()}catch(error){retryPanel('Unable to save the replay: '+error.message)}});
 window.addEventListener('vendetta-replay-limit',()=>{vendettaReplay.stop();storyPanel('<h2>MATCH TIME LIMIT</h2><p>This match exceeded 25 minutes of active play. No points were awarded. You can restart this match.</p><button class="primary" id="onlineLimitBack">BACK TO STORY</button>');$('onlineLimitBack').onclick=storyHome});
 const localRewards=rewardsPanel183;rewardsPanel183=function(){if(!window.vendettaOnlineConfig?.enabled)return localRewards();storyPanel('<div class="eyebrow">VERIFIED REWARDS</div><h1>YOUR REWARDS</h1><div id="storyWalletSlot"></div><p id="verifiedRewardStatus">Connect your wallet to check verified runs.</p><div class="row"><button class="primary" id="loadVerifiedRewards">CHECK VERIFIED REWARDS</button><button class="secondary" id="ecoBack">BACK TO STORY</button></div>');$('ecoBack').onclick=storyHome;$('loadVerifiedRewards').onclick=async()=>{try{if(!window.vendettaOnline)throw Error('Connect AGW first.');const replay=await loadPending(window.vendettaOnline.wallet);if(replay){pending=replay;retryPanel('A completed match is waiting for verification.');return}const {run,pendingRuns=[]}=await window.vendettaOnline.status();if(pendingRuns.length){$('verifiedRewardStatus').textContent='Verified runs ready to claim:';$('loadVerifiedRewards').hidden=true;for(const item of pendingRuns){const button=document.createElement('button');button.className='primary';button.textContent='CLAIM '+item.earned+' POINTS';button.onclick=()=>window.dispatchEvent(new CustomEvent('vendetta-claim',{detail:{runId:item.id}}));$('verifiedRewardStatus').after(button)}return}$('verifiedRewardStatus').textContent=run?(run.claimed?'Rewards already claimed.':run.closed?run.earned+' verified points ready to claim.':'Your current run is still active.'):'No verified run yet.';if(run?.closed&&!run.claimed&&run.earned>0){$('loadVerifiedRewards').textContent='CLAIM '+run.earned+' POINTS';$('loadVerifiedRewards').onclick=()=>window.dispatchEvent(new CustomEvent('vendetta-claim',{detail:{runId:run.id}}))}}catch(e){$('verifiedRewardStatus').textContent=e.message}}};
})();
